/**
 * The flagship 9 day Shimla → Spiti → Manali itinerary (the homepage route). The map road is
 * generated from the days (one forward stretch per travel day).
 */
import type { RouteContent } from '../types';

export const shimlaToSpiti: RouteContent = {
  slug: 'shimla-to-spiti',
  status: 'published',
  name: 'Private Shimla to Spiti Valley Road Trip',
  shortTitle: 'Shimla → Spiti → Manali',
  summary:
    'Private transportation via Kinnaur and Kaza, with seasonal Chandratal to Manali route when road access is confirmed.',
  startingLocation: 'Shimla',
  endingLocation: 'Manali',
  seasonality:
    'Kunzum Pass, Chandratal and the Manali side of the full circuit are seasonal. When access is closed or unsuitable, ask about a Kinnaur return from Kaza.',
  isFeatured: true,
  hero: {
    kicker: 'Spiti · Private transport',
    title: 'Shimla → Spiti → Manali.',
    titleAccent: 'Your private ride.',
    subtitle: '9 days by Innova Crysta via Kinnaur, Kaza and the seasonal Kunzum road.',
    media: 'hero-vehicles',
  },
  seo: {
    metaTitle: 'Shimla to Spiti Taxi: 9 Day Innova Crysta Circuit',
    metaDescription:
      'Daily private taxi route from Shimla through Kinnaur and Kaza, with the seasonal Chandratal to Manali crossing. Check the route for your dates on WhatsApp.',
    ogTitle: 'Private Shimla to Spiti Road Trip | Spiti Darshan',
    ogDescription:
      'Explore the 9 day private transport itinerary and start a WhatsApp conversation.',
  },
  vehicles: ['innova-crysta'],
  days: [
    {
      dayNumber: 1,
      subtitle: 'The first climb',
      title: 'Shimla → Sangla',
      mapLegLabel: 'Shimla → Sangla',
      shortDescription: 'Pine forests give way to the Baspa Valley.',
      note: 'Overnight: Sangla',
      overnight: 'sangla',
      media: 'day-kinnaur-valley',
      mapSegment: null,
      stops: [
        { name: 'Shimla', type: 'start', destination: 'shimla' },
        { name: 'Kufri', type: 'viewpoint', destination: 'kufri' },
        { name: 'Narkanda', type: 'stop', destination: 'narkanda' },
        { name: 'Rampur', type: 'stop', destination: 'rampur' },
        { name: 'Karcham', type: 'stop', destination: 'karcham' },
        { name: 'Sangla', type: 'overnight', destination: 'sangla' },
      ],
    },
    {
      dayNumber: 2,
      subtitle: "Kinnaur's valleys",
      title: 'Sangla → Kalpa',
      mapLegLabel: 'Sangla → Kalpa',
      shortDescription: "Chitkul's river valley, then Kalpa's mountain views.",
      note: 'Chitkul side trip depends on time and access. Overnight: Kalpa.',
      overnight: 'kalpa',
      media: 'day-kalpa-kinner-kailash',
      mapSegment: null,
      stops: [
        { name: 'Sangla', type: 'start', destination: 'sangla' },
        { name: 'Rakcham', type: 'stop', destination: 'rakcham' },
        { name: 'Chitkul', type: 'detour', destination: 'chitkul', optional: true },
        { name: 'Reckong Peo', type: 'stop', destination: 'reckong-peo' },
        { name: 'Kalpa', type: 'overnight', destination: 'kalpa' },
      ],
    },
    {
      dayNumber: 3,
      subtitle: 'Enter the cold desert',
      title: 'Kalpa → Tabo',
      mapLegLabel: 'Kalpa → Tabo',
      shortDescription: 'The landscape changes at every bend.',
      note: 'Gue is an optional detour, subject to timing. Overnight: Tabo.',
      overnight: 'tabo',
      media: 'day-nako',
      mapSegment: null,
      stops: [
        { name: 'Kalpa', type: 'start', destination: 'kalpa' },
        { name: 'Pooh', type: 'stop', destination: 'pooh' },
        { name: 'Nako', type: 'attraction', destination: 'nako' },
        { name: 'Gue', type: 'detour', destination: 'gue', optional: true },
        { name: 'Tabo', type: 'overnight', destination: 'tabo' },
      ],
    },
    {
      dayNumber: 4,
      subtitle: 'Old Spiti',
      title: 'Tabo → Kaza',
      mapLegLabel: 'Tabo → Kaza',
      shortDescription: 'Ancient monasteries and a valley of dramatic cliffs.',
      note: 'Pin Valley is an optional diversion. Overnight: Kaza.',
      overnight: 'kaza',
      media: 'day-dhankar',
      mapSegment: null,
      stops: [
        {
          name: 'Tabo Monastery',
          type: 'monastery',
          destination: 'tabo',
          attraction: 'tabo-monastery',
        },
        { name: 'Dhankar', type: 'monastery', destination: 'dhankar' },
        { name: 'Pin Valley', type: 'detour', destination: 'pin-valley', optional: true },
        { name: 'Kaza', type: 'overnight', destination: 'kaza' },
      ],
    },
    {
      dayNumber: 5,
      subtitle: 'Above Kaza',
      title: 'Key → Kibber → Chicham',
      mapLegLabel: 'Key → Kibber → Chicham',
      shortDescription: 'A monastery, high villages and a spectacular bridge.',
      note: 'A local sightseeing loop; overnight: Kaza.',
      overnight: 'kaza',
      media: 'day-key-monastery',
      mapSegment: null,
      stops: [
        { name: 'Kaza', type: 'start', destination: 'kaza' },
        { name: 'Key Monastery', type: 'monastery', attraction: 'key-monastery' },
        { name: 'Kibber', type: 'attraction', destination: 'kibber' },
        { name: 'Chicham Bridge', type: 'attraction', attraction: 'chicham-bridge' },
        {
          name: 'Return to Kaza',
          type: 'overnight',
          destination: 'kaza',
          mapLabel: 'Kaza · return',
        },
      ],
    },
    {
      dayNumber: 6,
      subtitle: 'The high village circuit',
      title: 'Langza → Hikkim → Komic',
      mapLegLabel: 'Langza → Hikkim → Komic',
      shortDescription: 'Small villages. Big Himalayan skies.',
      note: 'Local conditions and altitude may change the order of stops.',
      overnight: 'kaza',
      media: 'day-langza',
      mapSegment: null,
      stops: [
        { name: 'Kaza', type: 'start', destination: 'kaza' },
        { name: 'Langza', type: 'attraction', destination: 'langza' },
        { name: 'Hikkim', type: 'attraction', destination: 'hikkim' },
        { name: 'Komic', type: 'attraction', destination: 'komic' },
        {
          name: 'Return to Kaza',
          type: 'overnight',
          destination: 'kaza',
          mapLabel: 'Kaza · return',
        },
      ],
    },
    {
      dayNumber: 7,
      subtitle: 'Take it slow',
      title: 'Kaza, at your pace.',
      mapLegLabel: 'Kaza · flexible day',
      shortDescription: 'A little breathing room makes a better road trip.',
      note: 'Flexible time for rest, local walks or a weather buffer.',
      overnight: 'kaza',
      media: 'day-kaza',
      mapSegment: null,
      stops: [
        { name: 'Kaza', type: 'overnight', destination: 'kaza', mapLabel: 'Kaza · rest day' },
        { name: 'Local market', type: 'activity', showOnMap: false },
        { name: 'Rest', type: 'activity', showOnMap: false },
        { name: 'Weather buffer', type: 'activity', showOnMap: false },
      ],
    },
    {
      dayNumber: 8,
      subtitle: 'Seasonal mountain crossing',
      title: 'Kaza → Chandratal',
      mapLegLabel: 'Kaza → Chandratal',
      shortDescription: 'The high road opens only when conditions allow.',
      note: 'Seasonal road and accommodation must be confirmed before booking.',
      isSeasonal: true,
      overnight: 'chandratal',
      media: 'day-chandratal',
      mapSegment: null,
      stops: [
        { name: 'Kaza', type: 'start', destination: 'kaza' },
        { name: 'Losar', type: 'stop', destination: 'losar' },
        { name: 'Kunzum Pass', type: 'pass', attraction: 'kunzum-pass', seasonal: true },
        { name: 'Chandratal turn', type: 'stop' },
        {
          name: 'Chandratal',
          type: 'lake',
          destination: 'chandratal',
          seasonal: true,
          mapLabel: 'Chandratal · seasonal',
        },
      ],
    },
    {
      dayNumber: 9,
      subtitle: 'Complete the circuit',
      title: 'Chandratal → Manali',
      mapLegLabel: 'Chandratal → Manali',
      shortDescription: 'Across the Chandra Valley, into Manali.',
      note: 'Seasonal circuit only. When Kunzum is closed, ask about returning via Kinnaur.',
      isSeasonal: true,
      overnight: 'manali',
      media: 'day-atal-tunnel',
      mapSegment: null,
      stops: [
        { name: 'Chandratal', type: 'start', destination: 'chandratal', seasonal: true },
        { name: 'Batal', type: 'stop', destination: 'batal' },
        { name: 'Gramphu', type: 'stop', destination: 'gramphu' },
        { name: 'Atal Tunnel', type: 'attraction', attraction: 'atal-tunnel' },
        { name: 'Manali', type: 'overnight', destination: 'manali' },
      ],
    },
  ],
};
