/**
 * The flagship 9-day Shimla → Spiti → Manali itinerary (the homepage route). Map segments are the
 * eight hand-drawn road curves of the approved design.
 */
import type { RouteContent } from '../types';

// The eight hand-drawn road segments of the approved map (viewBox 3200×110).
const SEG = [
  'M 30 58 C 98 27 142 81 210 62 C 290 40 360 30 485 56',
  'M 485 56 C 560 85 612 16 691 45 C 774 75 821 32 896 58',
  'M 896 58 C 975 90 1041 28 1125 48 C 1203 74 1280 20 1387 56',
  'M 1387 56 C 1482 93 1535 19 1615 43 C 1673 61 1711 81 1765 56',
  'M 1765 56 C 1805 20 1900 8 1970 39 C 2017 70 1840 96 1765 56',
  'M 1765 56 C 1818 94 2058 102 2140 79 C 2202 41 1910 12 1765 56',
  'M 1765 56 C 1892 22 2185 75 2330 58 C 2456 47 2498 22 2590 54',
  'M 2590 54 C 2700 91 2765 22 2862 43 C 2963 67 3068 25 3170 53',
] as const;

export const shimlaToSpiti: RouteContent = {
  slug: 'shimla-to-spiti',
  status: 'published',
  name: 'Private Shimla to Spiti Valley Road Trip',
  shortTitle: 'Shimla → Spiti → Manali',
  summary:
    'Private transportation via Kinnaur and Kaza, with seasonal Chandratal to Manali route when road access is confirmed.',
  startingLocation: 'Shimla',
  endingLocation: 'Manali',
  seasonality:
    'Kunzum Pass, Chandratal and the Manali side of the full circuit are seasonal. When access is closed or unsuitable, ask about a Kinnaur-side return from Kaza.',
  isFeatured: true,
  hero: {
    kicker: 'Spiti · Private transport',
    title: 'Shimla → Spiti → Manali.',
    titleAccent: 'Your private ride.',
    media: 'hero-vehicles',
  },
  seo: {
    metaTitle: 'Shimla to Spiti Taxi — 9-Day Private Innova Crysta Circuit',
    metaDescription:
      'Day-wise private taxi route from Shimla through Kinnaur and Kaza, with the seasonal Chandratal–Manali crossing. Check the route for your dates on WhatsApp.',
    ogTitle: 'Private Shimla to Spiti Road Trip | Spiti Darshan',
    ogDescription:
      'Explore the 9-day private transport itinerary and start a WhatsApp conversation.',
  },
  vehicles: ['innova-crysta'],
  days: [
    {
      dayNumber: 1,
      subtitle: 'The first climb',
      title: 'Shimla → Sangla',
      mapLegLabel: 'Shimla → Sangla',
      shortDescription: 'Pine forests give way to the Baspa Valley.',
      note: 'Overnight: Sangla',
      overnight: 'sangla',
      media: 'hero-vehicles',
      mapSegment: SEG[0],
      stops: [
        { name: 'Shimla', type: 'start', destination: 'shimla' },
        { name: 'Kufri', type: 'viewpoint', destination: 'kufri' },
        { name: 'Narkanda', type: 'stop', destination: 'narkanda' },
        { name: 'Rampur', type: 'stop', destination: 'rampur' },
        { name: 'Karcham', type: 'stop', destination: 'karcham' },
        { name: 'Sangla', type: 'overnight', destination: 'sangla' },
      ],
    },
    {
      dayNumber: 2,
      subtitle: "Kinnaur's valleys",
      title: 'Sangla → Kalpa',
      mapLegLabel: 'Sangla → Kalpa',
      shortDescription: "Chitkul's river valley, then Kalpa's mountain views.",
      note: 'Chitkul side trip depends on time and access. Overnight: Kalpa.',
      overnight: 'kalpa',
      media: 'day-kinnaur-valley',
      mapSegment: SEG[1],
      stops: [
        { name: 'Sangla', type: 'start', destination: 'sangla' },
        { name: 'Rakcham', type: 'stop', destination: 'rakcham' },
        { name: 'Chitkul', type: 'detour', destination: 'chitkul', optional: true },
        { name: 'Reckong Peo', type: 'stop', destination: 'reckong-peo' },
        { name: 'Kalpa', type: 'overnight', destination: 'kalpa' },
      ],
    },
    {
      dayNumber: 3,
      subtitle: 'Enter the cold desert',
      title: 'Kalpa → Tabo',
      mapLegLabel: 'Kalpa → Tabo',
      shortDescription: 'The landscape changes at every bend.',
      note: 'Gue is an optional detour, subject to timing. Overnight: Tabo.',
      overnight: 'tabo',
      media: 'day-cold-desert',
      mapSegment: SEG[2],
      stops: [
        { name: 'Kalpa', type: 'start', destination: 'kalpa' },
        { name: 'Pooh', type: 'stop', destination: 'pooh' },
        { name: 'Nako', type: 'attraction', destination: 'nako' },
        { name: 'Gue', type: 'detour', destination: 'gue', optional: true },
        { name: 'Tabo', type: 'overnight', destination: 'tabo' },
      ],
    },
    {
      dayNumber: 4,
      subtitle: 'Old Spiti',
      title: 'Tabo → Kaza',
      mapLegLabel: 'Tabo → Kaza',
      shortDescription: 'Ancient monasteries and a valley of dramatic cliffs.',
      note: 'Pin Valley is an optional diversion. Overnight: Kaza.',
      overnight: 'kaza',
      media: 'day-old-spiti',
      mapSegment: SEG[3],
      stops: [
        {
          name: 'Tabo Monastery',
          type: 'monastery',
          destination: 'tabo',
          attraction: 'tabo-monastery',
        },
        { name: 'Dhankar', type: 'monastery', destination: 'dhankar' },
        { name: 'Pin Valley', type: 'detour', destination: 'pin-valley', optional: true },
        { name: 'Kaza', type: 'overnight', destination: 'kaza' },
      ],
    },
    {
      dayNumber: 5,
      subtitle: 'Above Kaza',
      title: 'Key → Kibber → Chicham',
      mapLegLabel: 'Key → Kibber → Chicham',
      shortDescription: 'A monastery, high villages and a spectacular bridge.',
      note: 'A local sightseeing loop; overnight: Kaza.',
      overnight: 'kaza',
      media: 'fleet-parked',
      mapSegment: SEG[4],
      stops: [
        { name: 'Kaza', type: 'start', destination: 'kaza' },
        { name: 'Key Monastery', type: 'monastery', attraction: 'key-monastery' },
        { name: 'Kibber', type: 'attraction', destination: 'kibber' },
        { name: 'Chicham Bridge', type: 'attraction', attraction: 'chicham-bridge' },
        {
          name: 'Return to Kaza',
          type: 'overnight',
          destination: 'kaza',
          mapLabel: 'Kaza · return',
        },
      ],
    },
    {
      dayNumber: 6,
      subtitle: 'The high-village circuit',
      title: 'Langza → Hikkim → Komic',
      mapLegLabel: 'Langza → Hikkim → Komic',
      shortDescription: 'Small villages. Big Himalayan skies.',
      note: 'Local conditions and altitude may change the order of stops.',
      overnight: 'kaza',
      // The approved page's day-6 remote photo no longer exists upstream (HTTP 404), so it has
      // always rendered its CSS fallback — the hero vehicle photo. Kept identical.
      media: 'hero-vehicles',
      mapSegment: SEG[5],
      stops: [
        { name: 'Kaza', type: 'start', destination: 'kaza' },
        { name: 'Langza', type: 'attraction', destination: 'langza' },
        { name: 'Hikkim', type: 'attraction', destination: 'hikkim' },
        { name: 'Komic', type: 'attraction', destination: 'komic' },
        {
          name: 'Return to Kaza',
          type: 'overnight',
          destination: 'kaza',
          mapLabel: 'Kaza · return',
        },
      ],
    },
    {
      dayNumber: 7,
      subtitle: 'Take it slow',
      title: 'Kaza, at your pace.',
      mapLegLabel: 'Kaza · flexible day',
      shortDescription: 'A little breathing room makes a better road trip.',
      note: 'Flexible time for rest, local walks or a weather buffer.',
      overnight: 'kaza',
      media: 'hero-vehicles',
      mapSegment: null,
      stops: [
        { name: 'Kaza', type: 'overnight', destination: 'kaza', mapLabel: 'Kaza · rest day' },
        { name: 'Local market', type: 'activity', showOnMap: false },
        { name: 'Rest', type: 'activity', showOnMap: false },
        { name: 'Weather buffer', type: 'activity', showOnMap: false },
      ],
    },
    {
      dayNumber: 8,
      subtitle: 'Seasonal mountain crossing',
      title: 'Kaza → Chandratal',
      mapLegLabel: 'Kaza → Chandratal',
      shortDescription: 'The high road opens only when conditions allow.',
      note: 'Seasonal road and accommodation must be confirmed before booking.',
      isSeasonal: true,
      overnight: 'chandratal',
      media: 'day-high-pass',
      mapSegment: SEG[6],
      stops: [
        { name: 'Kaza', type: 'start', destination: 'kaza' },
        { name: 'Losar', type: 'stop', destination: 'losar' },
        { name: 'Kunzum Pass', type: 'pass', attraction: 'kunzum-pass', seasonal: true },
        { name: 'Chandratal turn', type: 'stop' },
        {
          name: 'Chandratal',
          type: 'lake',
          destination: 'chandratal',
          seasonal: true,
          mapLabel: 'Chandratal · seasonal',
        },
      ],
    },
    {
      dayNumber: 9,
      subtitle: 'Complete the circuit',
      title: 'Chandratal → Manali',
      mapLegLabel: 'Chandratal → Manali',
      shortDescription: 'Across the Chandra Valley, into Manali.',
      note: 'Seasonal circuit only. When Kunzum is closed, ask about returning via Kinnaur.',
      isSeasonal: true,
      overnight: 'manali',
      media: 'day-chandra-valley',
      mapSegment: SEG[7],
      stops: [
        { name: 'Chandratal', type: 'start', destination: 'chandratal', seasonal: true },
        { name: 'Batal', type: 'stop', destination: 'batal' },
        { name: 'Gramphu', type: 'stop', destination: 'gramphu' },
        { name: 'Atal Tunnel', type: 'attraction', attraction: 'atal-tunnel' },
        { name: 'Manali', type: 'overnight', destination: 'manali' },
      ],
    },
  ],
};
