/**
 * Winter Spiti, 7 nights / 8 days: Shimla → Kinnaur → Kaza and back via Kinnaur (the winter road).
 * A sample plan; the car price is owner-supplied and also drives the homepage winter offer.
 */
import type { RouteContent } from '../types';

export const winterSpiti8Days: RouteContent = {
  slug: 'winter-spiti-8-days',
  status: 'published',
  name: 'Winter Spiti Road Trip, 7 nights / 8 days',
  shortTitle: 'Winter Spiti — 7 nights / 8 days',
  summary:
    'White Spiti by Innova Crysta with a driver: Kinnaur, Tabo and Kaza in snow, returning via Kinnaur.',
  startingLocation: 'Shimla',
  endingLocation: 'Shimla',
  seasonality:
    'Winter roads depend on snow and access. Stops and timings are confirmed for your dates, and snow chains are used when needed.',
  isFeatured: false,
  carPrice: 40000,
  hero: {
    kicker: 'Winter Spiti · Innova Crysta',
    title: 'Winter Spiti.',
    titleAccent: '7 nights, 8 days.',
    subtitle: 'Shimla to Kaza and back via Kinnaur, with a driver for your group.',
    media: 'day-langza',
  },
  seo: {
    metaTitle: 'Winter Spiti 7N/8D by Innova Crysta',
    metaDescription:
      'Winter Spiti in 8 days by Innova Crysta with a driver: Kalpa, Nako, Tabo, Kaza, Key and Langza in snow. ₹40,000 car price for your group. Plan on WhatsApp.',
    ogTitle: 'Winter Spiti, 7 nights / 8 days | Spiti Darshan',
    ogDescription:
      'White Spiti by Innova Crysta: the 8-day winter road trip from Shimla, day by day.',
  },
  vehicles: ['innova-crysta'],
  days: [
    {
      dayNumber: 1,
      subtitle: 'Into the snow',
      title: 'Shimla → Sangla',
      mapLegLabel: 'Shimla → Sangla',
      shortDescription: 'Pine forests give way to the snowy Baspa Valley.',
      note: 'Snow chains go on when the road needs them. Overnight: Sangla.',
      overnight: 'sangla',
      media: 'day-kinnaur-valley',
      mapSegment: null,
      stops: [
        { name: 'Shimla', type: 'start', destination: 'shimla' },
        { name: 'Narkanda', type: 'stop', destination: 'narkanda' },
        { name: 'Rampur', type: 'stop', destination: 'rampur' },
        { name: 'Karcham', type: 'stop', destination: 'karcham' },
        { name: 'Sangla', type: 'overnight', destination: 'sangla' },
      ],
    },
    {
      dayNumber: 2,
      subtitle: "Kinnaur's white valleys",
      title: 'Sangla → Kalpa',
      mapLegLabel: 'Sangla → Kalpa',
      shortDescription: 'Chitkul in snow, then Kinner Kailash from Kalpa.',
      note: 'Chitkul in the morning, Kalpa by evening. Overnight: Kalpa.',
      overnight: 'kalpa',
      media: 'day-kalpa-kinner-kailash',
      mapSegment: null,
      stops: [
        { name: 'Sangla', type: 'start', destination: 'sangla' },
        { name: 'Rakcham', type: 'stop', destination: 'rakcham' },
        { name: 'Chitkul', type: 'detour', destination: 'chitkul' },
        { name: 'Reckong Peo', type: 'stop', destination: 'reckong-peo' },
        { name: 'Kalpa', type: 'overnight', destination: 'kalpa' },
      ],
    },
    {
      dayNumber: 3,
      subtitle: 'Enter the cold desert',
      title: 'Kalpa → Tabo',
      mapLegLabel: 'Kalpa → Tabo',
      shortDescription: 'Frozen Nako and the quiet road into Spiti.',
      note: 'Visit Nako and Gue before arriving in Tabo for the night.',
      overnight: 'tabo',
      media: 'day-nako',
      mapSegment: null,
      stops: [
        { name: 'Kalpa', type: 'start', destination: 'kalpa' },
        { name: 'Pooh', type: 'stop', destination: 'pooh' },
        { name: 'Nako', type: 'attraction', destination: 'nako' },
        { name: 'Gue', type: 'attraction', destination: 'gue' },
        { name: 'Tabo', type: 'overnight', destination: 'tabo' },
      ],
    },
    {
      dayNumber: 4,
      subtitle: 'Old Spiti in winter',
      title: 'Tabo → Kaza',
      mapLegLabel: 'Tabo → Kaza',
      shortDescription: 'Ancient monasteries, cliffs and tea at the Ice Cafe.',
      note: 'Ice Cafe Lingti when it is open. Overnight: Kaza.',
      overnight: 'kaza',
      media: 'day-dhankar',
      mapSegment: null,
      stops: [
        {
          name: 'Tabo Monastery',
          type: 'monastery',
          destination: 'tabo',
          attraction: 'tabo-monastery',
        },
        { name: 'Dhankar', type: 'monastery', destination: 'dhankar' },
        { name: 'Ice Cafe Lingti', type: 'activity', showOnMap: false },
        { name: 'Kaza', type: 'overnight', destination: 'kaza' },
      ],
    },
    {
      dayNumber: 5,
      subtitle: 'Snow leopard country',
      title: 'Key → Kibber → Chicham',
      mapLegLabel: 'Key → Kibber → Chicham',
      shortDescription: 'A snowy monastery, high villages and the snow leopard slopes.',
      note: 'Snow leopard spotting around Kibber; sightings vary. Overnight: Kaza.',
      overnight: 'kaza',
      media: 'day-key-monastery',
      mapSegment: null,
      stops: [
        { name: 'Kaza', type: 'start', destination: 'kaza' },
        { name: 'Key Monastery', type: 'monastery', attraction: 'key-monastery' },
        { name: 'Kibber', type: 'attraction', destination: 'kibber' },
        { name: 'Snow leopard spotting', type: 'activity', showOnMap: false },
        { name: 'Chicham Bridge', type: 'attraction', attraction: 'chicham-bridge' },
        {
          name: 'Return to Kaza',
          type: 'overnight',
          destination: 'kaza',
          mapLabel: 'Kaza · return',
        },
      ],
    },
    {
      dayNumber: 6,
      subtitle: 'White villages',
      title: 'Langza → Hikkim → Komic',
      mapLegLabel: 'Langza → Hikkim → Komic',
      shortDescription: 'Snow villages under huge Himalayan skies.',
      note: 'Snow and road access may change the order of stops. Overnight: Kaza.',
      overnight: 'kaza',
      media: 'day-langza',
      mapSegment: null,
      stops: [
        { name: 'Kaza', type: 'start', destination: 'kaza' },
        { name: 'Langza', type: 'attraction', destination: 'langza' },
        { name: 'Hikkim', type: 'attraction', destination: 'hikkim' },
        { name: 'Komic', type: 'attraction', destination: 'komic' },
        {
          name: 'Return to Kaza',
          type: 'overnight',
          destination: 'kaza',
          mapLabel: 'Kaza · return',
        },
      ],
    },
    {
      dayNumber: 7,
      subtitle: 'The road back',
      title: 'Kaza → Kalpa',
      mapLegLabel: 'Kaza → Kalpa',
      shortDescription: 'Back down the Spiti valley into Kinnaur.',
      note: 'The return follows the winter road via Kinnaur. Overnight: Kalpa.',
      overnight: 'kalpa',
      media: 'day-kaza',
      mapSegment: null,
      stops: [
        { name: 'Kaza', type: 'start', destination: 'kaza' },
        { name: 'Tabo', type: 'stop', destination: 'tabo' },
        { name: 'Nako', type: 'stop', destination: 'nako' },
        { name: 'Reckong Peo', type: 'stop', destination: 'reckong-peo' },
        { name: 'Kalpa', type: 'overnight', destination: 'kalpa' },
      ],
    },
    {
      dayNumber: 8,
      subtitle: 'Home with the snow',
      title: 'Kalpa → Shimla',
      mapLegLabel: 'Kalpa → Shimla',
      shortDescription: 'Down the Sutlej valley to Shimla.',
      note: 'Drop in Shimla. Ask us about other drop points.',
      overnight: 'shimla',
      media: 'day-kinnaur-valley',
      mapSegment: null,
      stops: [
        { name: 'Kalpa', type: 'start', destination: 'kalpa' },
        { name: 'Reckong Peo', type: 'stop', destination: 'reckong-peo' },
        { name: 'Rampur', type: 'stop', destination: 'rampur' },
        { name: 'Narkanda', type: 'stop', destination: 'narkanda' },
        { name: 'Shimla', type: 'overnight', destination: 'shimla' },
      ],
    },
  ],
};
